version: '3'

services:

  opencr:
    container_name: opencr
    image: intrahealth/opencr
    ports:
      - "3000:3000"
    depends_on:
      - fhir
      - opensearch
    restart: always
    environment:
      - NODE_ENV=cicd
    # networks: 
    #   - opencr

  fhir:
    container_name: hapi-fhir
    image: hapiproject/hapi:v5.1.0
    ports:
      - "8080:8080"
    # networks:
    #   - opencr

  opensearch:
    container_name: opensearch
    image: intrahealth/opensearch:latest
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data01:/usr/share/opensearch/data
      
    ports:
      - 9200:9200
      - 9600:9600
    # networks:
    #   - opencr


volumes:
  data01:
    driver: local

# networks:
#   opencr:
#     driver: bridge