name: compose
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose up -d
        run: docker-compose -f docker-compose.cicd.yml up -d
      - name: sleep
        run: sleep 240
      - name: wget
        run: wget --no-check-certificate  https://localhost:3000/crux/